USE [Corporerm_homolog]
GO

/****** Object:  View [dbo].[_Fluig_CUSTO]    Script Date: 16/06/2020 18:21:54 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO




CREATE VIEW [dbo].[_Fluig_CUSTO] AS

SELECT 

	GCCUSTO.CODCCUSTO
,	GCCUSTO.NOME
,	GCCUSTO.CODCCUSTO+" - "+GCCUSTO.NOME AS CUSTO_NOME
,	CODREDUZIDO

FROM GCCUSTO(NOLOCK) 
	
WHERE ATIVO='T' AND PERMITELANC='T'

GO

